import Head from 'next/head'
import { useContext, useEffect } from 'react';
import SiteContext from '../components/SiteContext'
import Navbar from '../components/Navbar'
import Slider from '../components/Slider'

export default function Contact() {

  const { current, setcurrent, position } = useContext(SiteContext);

  useEffect(() => {
    setcurrent(3)
  }, [])

  return (
    <div>
      <Head>
        <title>MINeD | Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navigation Bar */}
      <Navbar />

      <main id="contact">

        {/* Left Slider */}
        <Slider />

        {/* Main Content here */}
        <div id="content" >
          <section style={{
            transform: `translateY(-${position*80}vh)`
          }}>
            <div className='left'></div>
            <div className='right'></div>
          </section>
        </div>

      </main>
    </div>
  )
}
