import Head from 'next/head'
import { useContext, useEffect } from 'react';
import SiteContext from '../components/SiteContext'
import Navbar from '../components/Navbar'
import Slider from '../components/Slider'

export default function Home() {

  const { setcurrent, setsections, position } = useContext(SiteContext);

  useEffect(() => {
    setcurrent(0)
    setsections(4)
  }, [])

  return (
    <div>
      <Head>
        <title>MINeD | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navigation Bar */}
      <Navbar />

      <main id="home">

        {/* Left Slider */}
        <Slider />

        {/* Main Content here */}
        <div id="content" >
          <section style={{
            transform: `translateY(-${position*80}vh)`
          }}>
            <div className='left'>
              <h1>MINeD Hackathon!</h1>
              <button>Learn More</button>
            </div>
            <div className='right'>
              <h1>MINeD Hackathon!</h1>
              <button>Learn More</button>
            </div>
          </section>
          <section style={{
            transform: `translateY(-${position*80}vh)`
          }}>
            <div className='left'>
              <h1>MINeD Hackathon 2!</h1>
              <button>Learn More</button>
            </div>
            <div className='right'>
              <h1>MINeD Hackathon 2!</h1>
              <button>Learn More</button>
            </div>
          </section>
          <section style={{
            transform: `translateY(-${position*80}vh)`
          }}>
            <div className='left'>
              <h1>MINeD Hackathon 3!</h1>
              <button>Learn More</button>
            </div>
            <div className='right'>
              <h1>MINeD Hackathon 3!</h1>
              <button>Learn More</button>
            </div>
          </section>
          <section style={{
            transform: `translateY(-${position*80}vh)`
          }}>
            <div className='left'>
              <h1>MINeD Hackathon 4!</h1>
              <button>Learn More</button>
            </div>
            <div className='right'>
              <h1>MINeD Hackathon 4!</h1>
              <button>Learn More</button>
            </div>
          </section>
        </div>

      </main>
    </div>
  )
}
